name: gradeit
channels:
  - defaults
dependencies:
  - gdal=2.3.3
  - geos=3.7.1
  - ipykernel=5.1.0
  - ipython=7.5.0
  - jpeg=9b
  - matplotlib=3.0.3
  - numpy=1.16.3
  - pandas=0.24.2
  - python=3.7.3
  - requests=2.21.0
  - scipy=1.2.1
  - sqlalchemy=1.3.3
