name: gradeit_py3
channels:
  - defaults
dependencies:
  - gdal=2.3
  - matplotlib=3.1
  - numpy=1.18
  - pandas=1.0
  - pip=20.0
  - python=3.8
  - python-dateutil=2.8
  - requests=2.22
  - scipy=1.3
  - sqlite=3.31
  - urllib3=1.25

